import { todoType } from '../../types/todoType';

export const todoItemDummyData: todoType[] = [
  {
    id: '1',
    state: 'notStarted',
    title: 'やること1',
    creator: '佐藤',
    applicable: ['佐藤', '田中', '中村'],
    endDate: new Date('2000/01/01'),
  },
  {
    id: '2',
    state: 'inProgress',
    title: 'やること2',
    creator: '鈴木',
    applicable: ['鈴木', '高橋', '伊藤', '佐藤', '田中', '中村', '高橋', '山本'],
    endDate: new Date('2000/02/01'),
  },
  {
    id: '3',
    state: 'pendingApproval',
    title: 'やること3',
    creator: '高橋',
    applicable: ['高橋', '山本', '松本', '中川'],
    endDate: new Date('2000/03/01'),
  },
  {
    id: '4',
    state: 'completed',
    title: 'やること4',
    creator: '田中',
    applicable: ['田中', '佐藤', '木村', '加藤', '渡辺'],
    endDate: new Date('2000/04/01'),
  },
  {
    id: '5',
    state: 'onHold',
    title: 'やること5',
    creator: '伊藤',
    applicable: ['伊藤', '中村', '山田', '斉藤'],
    endDate: new Date('2000/05/01'),
  },
  //   {
  //     id: '6',
  //     state: 'notStarted',
  //     title: 'やること6',
  //     creator: '山本',
  //     applicable: ['山本', '松田', '藤井'],
  //     endDate: new Date('2000/06/01'),
  //   },
  //   {
  //     id: '7',
  //     state: 'inProgress',
  //     title: 'やること7',
  //     creator: '松田',
  //     applicable: ['松田', '石川', '福田', '大野'],
  //     endDate: new Date('2000/07/01'),
  //   },
  //   {
  //     id: '8',
  //     state: 'pendingApproval',
  //     title: 'やること8',
  //     creator: '渡辺',
  //     applicable: ['渡辺', '田辺', '村上', '竹内'],
  //     endDate: new Date('2000/08/01'),
  //   },
  //   {
  //     id: '9',
  //     state: 'completed',
  //     title: 'やること9',
  //     creator: '中川',
  //     applicable: ['中川', '石田', '本田', '平田'],
  //     endDate: new Date('2000/09/01'),
  //   },
  //   {
  //     id: '10',
  //     state: 'onHold',
  //     title: 'やること10',
  //     creator: '藤井',
  //     applicable: ['藤井', '山下', '川口', '三浦'],
  //     endDate: new Date('2000/10/01'),
  //   },
];
